name: TDR Tag and pre deploy
on:
  push:
    branches:
      - main
jobs:
  pre-deploy:
    uses: nationalarchives/tdr-github-actions/.github/workflows/lambda_build.yml@main
    with:
      lambda-name: service-unavailable
      repo-name: tdr-service-unavailable
      artifact-name: deployment
      artifact-file-type: zip
      artifact-path: .
      build-command: |
        npm ci
        npm run build-css
        ./create_deployment_package.sh
    secrets:
      MANAGEMENT_ACCOUNT: ${{ secrets.MANAGEMENT_ACCOUNT }}
      WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
  deploy:
    needs: pre-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - run: gh workflow run deploy.yml -f environment=intg -f to-deploy=${{ needs.pre-deploy.outputs.next-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
