name: TDR Run Lambda Tests
on:
  pull_request:
  push:
    branches-ignore:
      - master
      - release-*
permissions:
  id-token: write
  contents: read
jobs:
  test:
    uses: nationalarchives/tdr-github-actions/.github/workflows/tdr_test.yml@main
    with:
      repo-name: tdr-checksum
      test-command: |
        pip install -r requirements.txt
        python -m pytest test
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
